---
title: "Ejercicios"
author: "Curso Álgebra Lineal"
subtitle: Polinomios
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)

#Anclar con el ambiente de Python
library(reticulate)
use_virtualenv('../../../.env', required=TRUE)

library(Ryacas)
```

Resolver a mano

## Pregunta 1

**¿Son las siguientes expresiones algebraicas polinomios en 
\mbox{\boldmath$\mathbb{R}[x]$}? En caso afirmativo, ¿qué grado tienen?**

- \mbox{\boldmath $1+x+x^2+x^3+x^4+\cdots+x^n$ } Es un polinomio de grado $n$.
- \mbox{\boldmath $1+\frac{1}{x}+x^2+\frac{1}{x^3}$ } no es un polinomio ya que 
  algunos términos tienen exponente negativo.
- \mbox{\boldmath $1-x^{-2}$ } no es un polinomio ya que algunos términos tienen 
  exponente negativo.
- \mbox{\boldmath $\sqrt{x}+3$ } no es un polinomio ya que algunos términos no 
  tienen como exponente un natural.
- \mbox{\boldmath $x+x^2i$ }
- \mbox{\boldmath $(x+1)^2$ } representa un polinomio de grado 2.
- \mbox{\boldmath $x+x^5+x^{10001}$ } es un polinomio de grado 10001.

\newpage

## Pregunta 2

**\mbox{\boldmath Hallar $\alpha$ y $\beta$ para que $x^5-\alpha x+\beta$ sea 
divisible entre $x^2-4$, $\forall x$.}**

```{python, results='asis'}
from funciones import encontrar

encontrar(
    _dividendo = r'x^5 - \alpha x + \beta',
    _divisor = r'x^2-4',
    _variables = ['alpha', 'beta']
)
```


### Comprobando


```{python, results='asis'}

from funciones import comprobar2a4

comprobar2a4(
        _dividendo = r'x^5 - \alpha x + \beta', 
        _divisor = r'x^2-4', 
        variables = {'alpha': 16, 'beta': 0}
    )
    
```


\newpage

## Pregunta 3

**\mbox{\boldmath Hallar $\alpha$ y $\beta$ para que $x^3-\alpha x^2+\beta x+3$ 
sea divisible entre $x^2+x+1$, $\forall x$.}**

```{python, results='asis'}
from funciones import encontrar

encontrar(
    _dividendo = r'x^3-\alpha x^2+\beta x+3',
    _divisor = r'x^2+x+1',
    _variables = ['alpha', 'beta']
)
```


### Comprobando

```{python, results='asis'}

from funciones import comprobar2a4

comprobar2a4(
        _dividendo = r'x^3 -\alpha x^2+\beta x+3', 
        _divisor = r'x^2+x+1', 
        variables = {'alpha': -4, 'beta': 4}
    )
    
```

\newpage

## Pregunta 4

**\mbox{\boldmath Encontrar el valor de $\alpha$ para que al dividir 
$2x^3-2x^2-\alpha x+4$ entre $x-2$ dé resto 2, $\forall x$.}**

```{python, results='asis'}
from funciones import encontrar

encontrar(
    _dividendo = r'(2x^3 - 2x^2 - \alpha x + 4) - 2',
    _divisor = r'x-2',
    _variables = ['alpha']
)
```


### Comprobando

```{python, results='asis'}

from funciones import comprobar2a4

comprobar2a4(
        _dividendo = r'2x^3 - 2x^2 -\alpha x + 4', 
        _divisor = r'x - 2', 
        variables = {'alpha': 5}
    )
    
```


\newpage

## Pregunta 5

**\mbox{\boldmath Determinar el valor de $\alpha$ para que 
$2 x^3 - 2 x^2 - \alpha x + 4$ admita $x = 2$ como una de sus raíces.}**

```{python, results='asis'}

from latex2sympy2 import latex2sympy
from sympy import solve
from sympy.abc import alpha, x
from sympy.printing import latex

p = latex2sympy(r'2x^3 -2x^2 - \alpha x + 4')

for i in solve(p.subs([(x, 2)]), alpha):
  
  print(
    'Cuando $' + latex(alpha) + ' = ' + str(i) +'$ y $x = 2$' +   
    r' entonces $' + latex(p) + ' = ' + latex(p.subs([(x, 2), (alpha, i)])) +'$'
    )
  
```

\newpage

## Pregunta 6

**Dados los polinomios**

\begin{gather*}
\mbox{\boldmath  $p(x) = x^4-6x+1$ \qquad $q(x) = 3x^3-5x$ \qquad $r(x) = x^4-x^2+2$  }
\end{gather*}

**Realizar las siguientes operaciones y en cada uno de los polinomios 
resultantes, evaluar en \mbox{\boldmath $0$, $-2$ y $2$ }.**

- \mbox{\boldmath $p(x)+3q(x)+r(x)$ }


```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'p + 3q + r', 
  lis = [0, -2, 2]
  )
```


- \mbox{\boldmath $p(x)-[q(x)+5r(x)]$ }


```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'p-[q+5r]', 
  lis = [0, -2, 2]
  )
```


\newpage

- \mbox{\boldmath $p(x)+q(x) \cdot r(x)$ }

```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'p+qr', 
  lis = [0, -2, 2]
  )
```


- \mbox{\boldmath $[4p(x)+q(x)] \cdot r(x)$ }

```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'[4p+q]*r', 
  lis = [0, -2, 2]
  )
```

\newpage

- \mbox{\boldmath $\frac{p(x)}{q(x)}-r(x)$ }

```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'\frac{p}{q}-r', 
  lis = [0, -2, 2]
  )
```


- \mbox{\boldmath $\frac{p(x)}{r(x)} \cdot 2q(x)$ }


```{python, results='asis'}
from funciones import punto6

punto6(
  p = r'x^4-6x+1', 
  q = r'3x^3-5x', 
  r = r'x^4-x^2+2', 
  operacion = r'2q \cdot (\frac{p}{r})', 
  lis = [0, -2, 2]
  )
```

\newpage

## Pregunta 7

**Dividir los polinomios, en cada uno de los polinomios resultantes (división, 
divisor, dividendo y modulo), evaluar en \mbox{\boldmath $1$, $2$ y $3$ } **


- \mbox{\boldmath $x^7-x^5+x^2-3$ entre $x^4+x^3+x^2+x$ }


```{python, results='asis'}
from funciones import punto7

punto7(
  p_text = r'x^7-x^5+x^2-3', 
  q_text = r'x^4+x^3+x^2+x', 
  lis = [1, 2, 3]
  )
```

- \mbox{\boldmath $x^8+x^7-3x^6+x^5+2x^4+-3x^3+x^2-x-10$ entre 
  $x^4+x^3-x^2+x+1$ }

```{python, results='asis'}
from funciones import punto7

punto7(
  p_text = r'x^8+x^7-3x^6+x^5+2x^4+-3x^3+x^2-x-10', 
  q_text = r'x^4+x^3-x^2+x+1',
  lis = [1, 2, 3]
  )
```

\newpage

- \mbox{\boldmath $x^6-x^5+x^4-x^3+x^2-x+1$ entre $x+1$ }

```{python, results='asis'}
from funciones import punto7

punto7(
  p_text = r'x^6-x^5+x^4-x^3+x^2-x+1', 
  q_text = r'x+1', 
  lis = [1, 2, 3]
  )
```