---
title: "Tarea"
author: "Curso Álgebra Lineal"
date: "`r Sys.Date()`"
output: pdf_document
subtitle: Sistemas con R, Python y Octave
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Ejercicio 1

Resolver el siguiente sistema

$$
\left
  \{
  \begin{array}{rrrrrrrrrrrrr}
    10x_1 & + & 2x_2 & - & x_3 & + & x_4 &  &  & + & 10x_6 & = & 0 \\ 
    -x_1 & - & 3x_2 &  &  &  &  & - & x_5 & + & 5x_6 & = & 5 \\ 
     &  & -x_2 & + & 3x_3 & - & x_4 &  &  &  &  & = & 5 \\ 
    17x_1 & + & x_2 &  &  & + & 3x_4 & + & 5x_5 & - & 15x_6 & = & 4 \\ 
     &  & -10x_2 &  &  & - & 5x_4 & + & 3x_5 &  &  & = & -21 \\ 
    -3x_1 & + & x_2 & + & x_3 & + & x_4 & - & 2x_5 & + & 2x_6 & = & 11
  \end{array}
\right.
$$

Primero, comprobar el tipo de sistema (compatible determinado, compatible indeterminado o incompatible) con R, Python y Octave.

Después, en caso de haber solución, calcularla con R, Python y Octave. Finalmente, indicar la solución final junto con el procedimiento llevado a cabo.

# Ejercicio 2

Resolver el siguiente sistema

$$
\left
  \{
  \begin{array}{rrrrrrrrrrrrrrr}
    -2x_1 & + & 2x_2 & - & x_3 & + & x_4 &  &  & + & 4x_6 &  &  & = & 5\\ 
    -x_1 & - & 3x_2 &  &  &  &  & - & x_5 & + & 5x_6 & - & 2x_7 & = & 3\\ 
     &  & -x_2 & + & 3x_3 & - & x_4 &  &  &  &  &  &  & = & 5\\ 
     &  & x_2 &  &  & + & 3x_4 & - & 2x_5 & + & x_6 & + & 4x_7 & = & 0\\ 
     &  & -3x_2 &  &  & - & 5x_4 & + & 3x_5 &  &  & - & 2x_7 & = & 5\\ 
    -3x_1 & + & x_2 & + & x_3 & + & x_4 & - & 2x_5 & + & 2x_6 & + & x_7 & = & 0
  \end{array}
\right.
$$

Primero, comprobar el tipo de sistema (compatible determinado, compatible indeterminado o incompatible) con R, Python y Octave.

Después, en caso de haber solución, calcularla con R, Python y Octave. Finalmente, indicar la solución final junto con el procedimiento llevado a cabo.

# Ejercicio 3

Resolver el siguiente sistema

$$
\left
  \{
  \begin{array}{rrrrrrrrrrrrr}
    10x_1 & + & 2x_2 & - & x_3 & + & x_4 &  &  & + & 10x_6 & = & 0\\ 
    -x_1 & - & 3x_2 &  &  &  &  & - & x_5 & + & 5x_6 & = & 5\\ 
    9x_1 & - & x_2 & - & x_3 & + & x_4 & - & x_5 & + & 15x_6 & = & 0\\ 
    17x_1 & + & x_2 &  &  & + & 3x_4 & + & 5x_5 & - & 15x_6 & = & 4\\ 
     &  & -10x_2 &  &  & - & 5x_4 & + & 3x_5 &  &  & = & -21\\ 
    -3x_1 & + & x_2 & + & x_3 & + & x_4 & - & 2x_5 & + & 2x_6 & = & 11\\
  \end{array}
\right.
$$

Primero, comprobar el tipo de sistema (compatible determinado, compatible indeterminado o incompatible) con R, Python y Octave.

Después, en caso de haber solución, calcularla con R, Python y Octave. Finalmente, indicar la solución final junto con el procedimiento llevado a cabo.

# Ejercicio 4

Encuentra la matriz $X$, ya sea a mano o con R,Python u Octave, tal que

## Apartado (a)

$AX+3B = -5X$ donde las matrices $A$ y $B$ son: 

$$
A = \begin{pmatrix}
-6  &  -3\\ 
0  &  -3
\end{pmatrix}
\quad B = \begin{pmatrix}
-1  &  0\\ 
4  &  -2
\end{pmatrix}
$$

## Apartado (b)

$ACX+3B = 10I-X$ donde las matrices $A$, $B$, $C$ e $I$ son:

$$
A = 
\begin{pmatrix}
1  &  2\\ 0  &  2
\end{pmatrix}
\quad B= \begin{pmatrix}
2  &  -1\\ -1  &  5
\end{pmatrix}
\quad C = 
\begin{pmatrix}
2  &  6\\ -1  &  -0.5
\end{pmatrix}
\quad I=
\begin{pmatrix}
1  &  0 \\0  &  1
\end{pmatrix}
$$