---
title: "Sección 4 - Matrices"
author: "Curso Álgebra Lineal"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

## Ejercicio 1

**Dada la matriz**

$$A = \begin{pmatrix}5 & 0 & 3\\ 9 & 7 & 11\end{pmatrix}$$

**¿Cuáles serían los elementos** $a_{11}$ y $a_{13}$?

$$a_{11} = 5$$

$$a_{13} = 3$$

\newpage

## Ejercicio 2

**Dada la matriz**

$$
A = \begin{pmatrix}
2 & 3 & -1 & 2 \\
3 & 2 & 5 & 0 \\
-1 & 7 & 0 & 4 \\
-4 & 1 & -3 & 7
\end{pmatrix}
$$

**comprobar que se cumple** $A + (-A) = (-A) + A = O$.

$$
-A = 
- \begin{pmatrix}
2 & 3 & -1 & 2 \\
3 & 2 & 5 & 0 \\
-1 & 7 & 0 & 4 \\
-4 & 1 & -3 & 7
\end{pmatrix} =
\begin{pmatrix}
-2 & -3 & 1 & -2 \\
-3 & -2 & -5 & 0 \\
1 & -7 & 0 & -4 \\
4 & -1 & 3 & -7
\end{pmatrix}
$$

$$
A + (-A) = 
\begin{pmatrix}
2 & 3 & -1 & 2 \\
3 & 2 & 5 & 0 \\
-1 & 7 & 0 & 4 \\
-4 & 1 & -3 & 7
\end{pmatrix} + 
\begin{pmatrix}
-2 & -3 & 1 & -2 \\
-3 & -2 & -5 & 0 \\
1 & -7 & 0 & -4 \\
4 & -1 & 3 & -7
\end{pmatrix} = 
$$

$$
= \begin{pmatrix}
2 - 2 & 3 - 3 & -1 + 1 & 2 -2 \\
3 - 3 & 2 - 2 & 5 -5 & 0 - 0 \\
-1 + 1 & 7 - 7 & 0 -0 & 4 - 4 \\
-4 + 4 & 1 - 1& -3 + 3 & 7 -7
\end{pmatrix} = 
$$

$$
=
\begin{pmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix} =
$$

$$
= 0
$$

$$
(-A) + A = 
\begin{pmatrix}
-2 & -3 & 1 & -2 \\
-3 & -2 & -5 & 0 \\
1 & -7 & 0 & -4 \\
4 & -1 & 3 & -7
\end{pmatrix} +
\begin{pmatrix}
2 & 3 & -1 & 2 \\
3 & 2 & 5 & 0 \\
-1 & 7 & 0 & 4 \\
-4 & 1 & -3 & 7
\end{pmatrix} =
$$

$$
=
\begin{pmatrix}
-2 + 2 & -3 + 3& 1 -1 & -2 + 2 \\
-3 + 3  & -2 + 2& -5 + 5& 0 - 0 \\
1 - 1 & -7 + 7& 0 -0 & -4 + 4 \\
4 - 4 & -1 + 1 & 3 - 3 & -7 + 7
\end{pmatrix} =
$$

$$
=
\begin{pmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix} =
$$

$$
= 0
$$

\newpage

## Ejercicio 3

Se consideran las matrices con coeficientes en $\mathbb{R}$

$$
A = \begin{pmatrix}1&2\\3&4\end{pmatrix}
\quad
B = \begin{pmatrix}1&0&1\\0&1&0\end{pmatrix}
\quad
C = \begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
$$

Probar que $(AB)C = A(BC)$

$$
\left( AB \right) C= 
$$

$$
= 
\left(
\begin{pmatrix}
1&2\\3&4
\end{pmatrix}
\begin{pmatrix}
1&0&1\\
0&1&0
\end{pmatrix}
\right)
\begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
=
$$

$$
= 
\begin{pmatrix}
    1 \cdot 1 + 2 \cdot 0 
    & 
    1 \cdot 0 + 2 \cdot 1 
    & 
    1 \cdot 1 + 2 \cdot 0 
  \\
    3 \cdot 1 + 4 \cdot 0 
    & 
    3 \cdot 0 + 4 \cdot 1 
    & 
    3 \cdot 1 + 4 \cdot 0 
  \\
\end{pmatrix}
\begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
=
$$

$$
= 
\begin{pmatrix}
1 & 2 & 1 \\
3 & 4 & 3 \\
\end{pmatrix}
\begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
=
$$

$$
= 
\begin{pmatrix}
1 \cdot 1 + 2 \cdot 0 + 1 \cdot (-1) & 
1 \cdot (-1) + 2 \cdot 1 + 1 \cdot 0
\\
3 \cdot 1 + 4 \cdot 0 + 3 \cdot (-1) & 
3 \cdot (-1) + 4 \cdot 1 + 3 \cdot 0
\end{pmatrix}
=
$$

$$
= 
\begin{pmatrix}
 1 + 0 - 1
 & 
 -1 + 2 + 0
\\
 3 + 0 -3
 &
 -3 + 4 + 0
\end{pmatrix}
=
$$

$$
= 
\begin{pmatrix}
0 & 1 \\
0 & 1
\end{pmatrix}
$$

$$
A \left( B  C \right) = 
$$

$$
=
\begin{pmatrix}1&2\\3&4\end{pmatrix}
\left(
\begin{pmatrix}1&0&1\\0&1&0\end{pmatrix}
\begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
\right)
=
$$

$$
=
\begin{pmatrix}
    1&2
  \\
    3&4
\end{pmatrix}
\begin{pmatrix}
    1 \cdot 1 + 0 \cdot 0 + 1 \cdot (-1)
    &
    1 \cdot (-1) + 0 \cdot 1 + 1 \cdot 0
  \\
    0 \cdot 1 + 1 \cdot 0 + 0 \cdot (-1)
    &
    0 \cdot (-1) + 1 \cdot 1 + 0 \cdot 0
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1&2
  \\
    3&4
\end{pmatrix}
\begin{pmatrix}
    1-1 
    &
    -1
  \\
    0
    &
    1
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1&2
  \\
    3&4
\end{pmatrix}
\begin{pmatrix}
  0 
  & 
  -1 
  \\ 
  0 
  & 
  1
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1 \cdot 0 + 2 \cdot 0 
    &
    1 \cdot (-1) + 2 \cdot 1
  \\
    3 \cdot 0 + 4 \cdot 0 
    &
    3 \cdot (-1) + 4 \cdot 1
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    0
    &
    -1 + 2
  \\
    0
    &
    -3 + 4
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    0
    &
    1
  \\
    0
    &
    1
\end{pmatrix}
$$

\newpage

## Ejercicio 4

Escribe paso a paso la demostración de la propiedad distributiva del producto respecto de la suma.

queremos demostrar que $A(B + C) = AB + AC$

Donde:

$A \in \mathcal{M}_{m\times n}(\mathbb{K})$, con $A = (a_{ij})$

$B, C \in \mathcal{M}_{n\times p}(\mathbb{K})$, con $B = (b_{jk})$, $C = (c_{jk})$,

Por un lado,

$B + C = D$ donde $D = (d_{jk})_{n \times p}$ con $d_{jk} = b_{jk} + c_{jk}$ $\forall j=1,\dots,n,\ k=1,\dots,p$

Entonces $A(B + C) = AD = E$ donde $E = (e_{ik})_{m \times p}$, con

$$
e_{ik} = \sum_{j=1}^{n} a_{ij}d_{jk} = \sum_{j=1}^{n} a_{ij}(b_{jk} + c_{jk})
$$

Por otro lado,

$AB = F$ donde $F = (f_{ik})_{m \times p}$, con

$$
f_{ik} = \sum_{j=1}^{n} a_{ij}b_{jk}
$$

$AC = G$ donde $G = (g_{ik})_{m \times p}$, con

$$
g_{ik} = \sum_{j=1}^{n} a_{ij}c_{jk}
$$

$AB + AC = F + G = H$ donde $H = (h_{ik})_{m \times p}$, con

$$
h_{k} = \sum_{j=1}^{n} a_{ij}c_{jk} + \sum_{j=1}^{n} a_{ij}b_{jk}
$$

Pero

$$
\sum_{j=1}^{n} a_{ij}(b_{jk} + c_{jk})
= 
\sum_{j=1}^{n} (a_{ij}b_{jk} + a_{ij}c_{jk})
= 
\sum_{j=1}^{n} a_{ij}c_{jk} + \sum_{j=1}^{n} a_{ij}b_{jk}
$$

Entonces, $E = H$

Por consiguiente, $A(B+C) =AB+AC$

\newpage

## Ejercicio 5

Considerad las matrices con coeficientes en $\mathbb{R}$:

$$
A=\begin{pmatrix}1&0&1\\0&1&0\end{pmatrix}
\quad
B = \begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
$$

Probar que:

$$AI_3 = A$$

$$I_3B = B$$

$$
AI_3 = 
$$

$$
=
\begin{pmatrix}
1 & 0 & 1 \\
0 & 1 & 0
\end{pmatrix}
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1 \cdot 1 + 0 \cdot 0 + 1 \cdot 0 
    & 
    1 \cdot 0 + 0 \cdot 1 + 1 \cdot 0 
    & 
    1 \cdot 0 + 0 \cdot 0 + 1 \cdot 1 
  \\
    0 \cdot 1 + 1 \cdot 0 + 0 \cdot 0 
    & 
    0 \cdot 0 + 1 \cdot 1 + 0 \cdot 0 
    & 
    0 \cdot 0 + 1 \cdot 0 + 0 \cdot 1 
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1
    & 
    0
    & 
    1
  \\
    0
    & 
    1
    & 
    0
\end{pmatrix}
=
$$

$$
=A
$$

$$
I_3B = 
$$

$$
=
\begin{pmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
\end{pmatrix}
\begin{pmatrix}
  1 & -1\\
  0 & 1\\
  -1 & 0
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1 \cdot    1 + 0 \cdot 0 + 0 \cdot (-1)
    & 
    1 \cdot (-1) + 0 \cdot 1 + 0 \cdot 0
  \\
    0 \cdot    1 + 1 \cdot 0 + 0 \cdot (-1)
    & 
    0 \cdot (-1) + 1 \cdot 1 + 0 \cdot 0
  \\
    0 \cdot    1 + 0 \cdot 0 + 1 \cdot (-1)
    & 
    0 \cdot (-1) + 0 \cdot 1 + 1 \cdot 0
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
    1
    & 
    -1
  \\
    0
    & 
    1
  \\
   -1
    & 
    0
\end{pmatrix}
=
$$

$$= B$$

\newpage

## Ejercicio 6

Escribe paso a paso la demostración de la propiedad del elemento neutro del producto o elemento unidad tomando como ejemplo las demostraciones del ejercicio 5.

\hfill

Demostración que $AI_n = A$:

\hfill

Sean:

\hfill

$A \in \mathcal{M}_{m \times n}(\mathbb{K})$, con $A = (a_{jk})_{m \times n}$ $\forall j = 1, \dots, m, \ k = 1, \dots , n$

\hfill

$I_n \in \mathcal{M}_n(\mathbb{K})$, con $I_n = (i_{lk})_n$

Donde

si $l = k$ entonces $i_{lk} = 1$,

si $l \neq k$ entonces $i_{lk} = 0$

\hfill

$C = AI_n$, con $C = (c_{jk})_{m \times n}$ donde

$$
c_{jk} = 
\sum_{l = 1}^{n} a_{jl} i_{lk}
$$

Por consiguiente,

$$
c_{jk} = a_{jk} i_{kk}
$$

$$
c_{jk} = a_{jk}
$$

Por ende, $C = A$, lo que concluiría que $AI_n = A$

\newpage

Demostración que $I_m B = B$:

\hfill

Sean:

\hfill

$B \in \mathcal{M}_{m \times n}(\mathbb{K})$, con $B = (b_{jk})_{m \times n}$ $\forall j = 1, \dots, m, \ k = 1, \dots , n$

\hfill

$I_m \in \mathcal{M}_m(\mathbb{K})$, con $I_m = (i_{lk})_m$, donde

si $l = k$ entonces $i_{lk} = 1$,

si $l \neq k$ entonces $i_{lk} = 0$

Entonces, Sea $I_m B = B$, con $C = (c_{jk})_{m \times n}$ donde

$$
c_{jk} = 
\sum_{l = 1}^{m} i_{jl} b_{lk}
$$

Por consiguiente,

$$
c_{jk} = i_{jj} b_{jk}
$$

$$
c_{jk} = b_{jk}
$$

Por ende, $C = B$, lo que concluiría que $I_mB = B$

\newpage

## Ejercicio 7

Escribe paso a paso la demostración de la propiedad

$$
AI_n = 
I_mA
$$

tomando como ejemplo las demostraciones anteriores.

Partiendo de que

$$
AI_n = A
$$

y

$$
I_mA = A
$$

Se concluye que

$$
AI_n = I_mA
$$

\newpage

## Ejercicio 8

Propiedad distributiva del producto por escalares respecto de la suma.

$$
\lambda (A + B) = \lambda A + \lambda B,\ \lambda \in \mathbb{K}
$$

Escribe paso a paso la demostración de esta propiedad tomando como ejemplo las demostraciones anteriores.

$A \in \mathcal{M}_{m\times n}(\mathbb{K})$, con $A = (a_{ij})$

$B \in \mathcal{M}_{m\times n}(\mathbb{K})$, con $B = (b_{ij})$

$\lambda \in \mathbb{R}$

Por un lado,

$C = A + B$ con $C = (c_{ij})_{m \times n}$ donde $c_{ij} = a_{ij} + b_{ij}$

por lo cual $\lambda(A + B) = \lambda C = D = (d_{ij})_{m \times n}$

donde

$$
d{ij} 
= 
\lambda c_{ij} 
= 
\lambda (a_{ij} + b_{ij})
=
\lambda a_{ij} + \lambda b_{ij}
$$

Por otro lado,

$E = \lambda A$ como $E = (e_{ij})_{m \times n}$ donde $e_{ij} = \lambda a_{ij}$

$F = \lambda B$ como $F = (f_{ij})_{m \times n}$ donde $f_{ij} = \lambda b_{ij}$

$H = E + F$, como $H = (h_{jk})_{m \times n}$, donde

$$
h_{ij} = e_{ij} + f_{ij}
$$

$$
h_{ij} = \lambda a_{ij} + \lambda b_{ij}
$$

Por lo anterior se infiere que

$$
d{ij} = h{ij}
$$

Por lo cual, se concluye

$$
\lambda (A + B) = \lambda A + \lambda B,\ \lambda \in \mathbb{K}
$$

\newpage

## Ejercicio 9

Propiedades distributiva del producto por matrices respecto de la suma de escalares.

$$(\lambda +\mu) A = \lambda A + \mu A,\ \lambda, \mu \in \mathbb{K}$$

Escribe paso a paso la demostración de esta propiedad tomando como ejemplo las demostraciones anteriores.

$A \in \mathcal{M}_{m\times n}(\mathbb{K})$, con $A = (a_{ij})$

$\lambda$ y $\mu \in \mathbb{R}$

Por un lado,

$B = (\lambda +\mu) A$, con $B = (b_{ij})$, donde, $b_{ij} = (\lambda +\mu) a_{ij} = \lambda a_{ij} + \mu a_{ij}$

Por otro lado,

$C = \lambda A$ con $C = (c_{ij})_{m \times n}$ donde $c_{ij} = \lambda a_{ij}$

$D = \mu A$ con $D = (d_{ij})_{m \times n}$ donde $d_{ij} = \mu a_{ij}$

$E = C + D$ con $E = (e_{ij})_{m \times n}$

donde

$$
e_{ij} = \lambda a_{ij} + \mu a_{ij}
$$

Por lo anterior se infiere que

$$
e_{ij} = b_{ij}
$$

Por lo cual, se concluye

$$(\lambda + \mu) A = \lambda A + \mu A,\ \lambda, \mu \in \mathbb{K}$$

\newpage

## Ejercicio 10

Propiedad asociativa del producto de escalares por una matriz.

$$
(\lambda \mu)A = \lambda(\mu A), \ \lambda,\mu \in \mathbb{K}
$$

Escribe paso a paso la demostración de esta propiedad tomando como ejemplo las demostraciones anteriores.

$A \in \mathcal{M}_{m\times n}(\mathbb{K})$, con $A = (a_{ij})$

$\lambda$ y $\mu \in \mathbb{R}$

Por un lado,

$B = (\lambda \mu) A$, con $B = (b_{ij})$, donde, $b_{ij} = (\lambda \mu) a_{ij} = \lambda (\mu a_{ij})$

Por otro lado,

$D = \mu A$ con $D = (d_{ij})_{m \times n}$ donde $d_{ij} = \mu a_{ij}$

$C = \lambda D$ con $C = (c_{ij})_{m \times n}$,

donde $c_{ij} = \lambda d_{ij} = \lambda (\mu a_{ij})$

Por lo anterior se infiere que

$$
c_{ij} = b_{ij}
$$

Por lo cual, se concluye

$$
(\lambda \mu)A = \lambda(\mu A), \ \lambda,\mu \in \mathbb{K}
$$

\newpage

## Ejercicio 11

Propiedad asociativa del producto de un escalar por dos matrices.

$$
\lambda (AB) = (\lambda A)B,\ \lambda \in \mathbb{K}
$$

Escribe paso a paso la demostración de esta propiedad tomando como ejemplo las demostraciones anteriores.

$\lambda$ y $\mu \in \mathbb{R}$

$A \in \mathcal{M}_{m \times n}(\mathbb{K})$, con $A = (a_{ij})$

$B \in \mathcal{M}_{n \times p}(\mathbb{K})$, con $B = (b_{jk})$

Por un lado,

$C = AB$, con $C = (c_{ik})_{m \times p}$,

donde,

$$
c_{ik} = \sum_{j = 1}^{m} a_{ij} b_{jk}
$$

$D = \lambda D = \lambda (AB)$, con $D = (d_{ik})_{m \times p}$

donde

$$
d_{ik} = 
\lambda c_{ik} = 
\lambda \sum_{j = 1}^{m} a_{ij} b_{jk} = 
\lambda \sum_{j = 1}^{m} a_{ij} b_{jk}
$$

Por otro lado,

$E = \lambda A$ con $E = (e_{ij})_{m \times n}$ donde $e_{ij} = \lambda a_{ij}$

$F = EB = (\lambda A) B$ con $F = (f_{ik})_{m \times p}$,

donde

$$
f_{ik} = 
\sum_{j = 1}^{m} e_{ij} b_{jk} = 
\sum_{j = 1}^{m} (\lambda a_{ij}) b_{jk}
$$

debido a que

$$
\sum_{j = 1}^{m} (\lambda a_{ij}) b_{jk}
=
\lambda \sum_{j = 1}^{m} a_{ij} b_{jk}
$$

Por lo cual, se concluye

$$
\lambda (AB) = (\lambda A)B,\ \lambda \in \mathbb{K}
$$

\newpage

## Ejercicio 12.

Ley de simplificación. No se cumple la ley de simplificación en un producto.

Ejemplo

$$
A = \begin{pmatrix}0&1\\0&2\end{pmatrix},\ 
B=\begin{pmatrix}1&1\\3&4\end{pmatrix},\ 
C=\begin{pmatrix}2&5\\3&4\end{pmatrix}
\in\mathcal{M}_2(\mathbb{R})
$$

satisfacen $AB=AC$, pero en cambio $B\ne C$

Comprueba que efectivamente $AB=AC$

\newpage

## Ejercicio 13.

Dadas

$$
A=\begin{pmatrix}1&0&0&0\\0&5&0&0\\0&0&-3&0\\0&0&0&2\end{pmatrix}
\qquad 
B=\begin{pmatrix}-2&0&0&0\\0&6&0&0\\0&0&3&0\\0&0&0&9\end{pmatrix}
$$

comprobad que $AB$ y $BA$ son matrices diagonales.

\newpage

## Ejercicio 14.

Dadas

$$
A=\begin{pmatrix}1&-1&4&3\\0&5&-2&1\\0&0&-3&7\\0&0&0&2\end{pmatrix}
\qquad 
B=\begin{pmatrix}-2&1&-1&2\\0&6&0&3\\0&0&3&-5\\0&0&0&-2\end{pmatrix}
$$

comprobad que $AB$ y $BA$ son matrices triangulares superiores.

\newpage

## Ejercicio 15.

Transpuesta de una suma.

$$\left(\sum_{i=1}^r A_i\right)^t=\sum_{i=1}^rA_i^t$$

Escribe paso a paso la demostración de esta propiedad

\newpage

## Ejercicio 16.

Comprobar que dadas

$$
A = \begin{pmatrix}2&3\\3&2\\-1&0\end{pmatrix}
\qquad 
B=\begin{pmatrix}1&0\\3&6\\3&-2\end{pmatrix}
\qquad 
C = \begin{pmatrix}-2&4\\0&5\\7&2\end{pmatrix}
$$

$$(A+B+C)^t=A^t+B^t+C^t$$

\newpage

## Ejercicio 17.

Probad que

$$(AB)^t=B^tA^t$$

donde

$$
A=\begin{pmatrix}1&0&1\\0&1&0\end{pmatrix}
\quad 
B = \begin{pmatrix}1&-1\\0&1\\-1&0\end{pmatrix}
$$

\newpage

## Ejercicio 18.

Transpuesta de un producto.

Escribe paso a paso la demostración de esta propiedad

Si $A\in\mathcal{M}_{m\times n}(\mathbb{K})$ y

$$(AB)^t=B^tA^t\in\mathcal{M}_{p\times m}(\mathbb{K})$$

$B\in\mathcal{M}_{n\times p}(\mathbb{K})$, entonces la traspuesta del producto de $A$ por $B$ es el producto de las traspuestas pero con orden cambiado, es decir:

\newpage

## Ejercicio 19.

siendo

$$A = \begin{pmatrix}1&2&3&4\\2&-1&5&6\\3&5&1&7\\4&6&7&-1\end{pmatrix}$$

Calculad $A^t$ y veréis que $A^t=A$, es decir que $A$ es una matriz simétrica.

\newpage

## Ejercicio 20.

siendo

$$A = \begin{pmatrix}0&2&3&4\\-2&0&5&6\\-3&-5&0&7\\-4&-6&-7&0\end{pmatrix}$$

Calculad $A^t$ y veréis que $A^t=-A$, es decir que $A$ es una matriz anti-simétrica.

\newpage

## Ejercicio 21.

$A = \begin{pmatrix}1&1&0\\0&1&0\\1&0&1\end{pmatrix}$ es una matriz regular cuya inversa es $A^{-1}=\begin{pmatrix}1&-1&0\\0&1&0\\-1&1&1\end{pmatrix}$

Comprobad que efectivamente $AA^{-1}=A^{-1}A=I_3$

\newpage

## Ejercicio 22.

Matriz ortogonal.

siendo

$$A = \frac{1}{3}\begin{pmatrix}2&-2&1\\2&1&-2\\1&2&2\end{pmatrix}$$

Comprobad que $A^tA=I_3$, es decir, $A$ es ortogonal

\newpage

## Ejercicio 23.

Sean

$$
A = \begin{pmatrix}1&2\\7&8\end{pmatrix}
\qquad 
B=\begin{pmatrix}1&3\\-1&0\end{pmatrix}
$$

de donde

$$A^{-1} = -\frac{1}{6}\begin{pmatrix}8&-2\\-7&1\end{pmatrix}\qquad B^{-1}=\frac{1}{3}\begin{pmatrix}0&-3\\1&1\end{pmatrix}$$ Comprobad que $B^{-1}A^{-1}=(AB)^{-1}$ donde $(AB)^{-1}=-\frac{1}{18}\begin{pmatrix}21&-3\\1&-1\end{pmatrix}$

\newpage

## Ejercicio 24.

Demostración

Para probar $(AB)^{-1}=B^{-1}A^{-1}$, lo que haremos será ver que

$$(AB)(B^{-1}A^{-1}) = (B^{-1}A^{-1})(AB) = I_n$$

Por un lado, por la propiedad asociativa y como $B^{-1}$ es la inversa de $B$, tenemos

$$(AB)(B^{-1}A^{-1}) = A(BB^{-1})A^{-1} = AI_nA^{-1} = AA^{-1}$$

ya que, recordemos, la matriz identidad $I_n$ actúa como elemento neutro del producto de matrices. Ahora, como $A^{-1}$ es la inversa de $A$, se tiene que

$$(AB)(B^{-1}A^{-1}) = AA^{-1} = I_n$$ tal y como queríamos demostrar.

Acabar la demostración siguiendo como modelo la parte que se ha llevado a cabo hasta el momento.

\newpage

## Ejercicio 25

-   Dad definiciones equivalentes para las matrices escalonadas por columnas y matrices escalonadas reducidas por columnas.

-   Poned dos ejemplos de cada tipo de matriz.

\newpage

## Ejercicio 26

Considerad la matriz $A\in\mathcal{M}_{3\times 4}(\mathbb{R})$ dada por

$$A=\begin{pmatrix}1&1&3&5\\2&4&3&-2\\-2&2&-1&3\end{pmatrix}$$

Calculad su matriz escalonada y su escalonada reducida por filas.

\newpage

## Ejercicio 27

Considerad la matriz $A\in\mathcal{M}_{3\times 5}(\mathbb{R})$ dada por

$$A=\begin{pmatrix}0&0&3&5&-1\\1&0&4&-1&2\\2&3&0&-2&3\end{pmatrix}$$

Calculad su matriz escalonada y su escalonada reducida por filas.

\newpage

## Ejercicio 28

-   Calculad el rango de

$$A=\begin{pmatrix}1&1&3&5\\2&4&3&-2\\-2&2&-1&3\end{pmatrix}$$

-   Calculad el rango de $$B = \begin{pmatrix}1&3&1\\0&3&-2\\2&2&3\end{pmatrix}$$

\newpage

## Ejercicio 29

Sea $A$ la matriz cuadrada $A\in\mathcal{M}_n(\mathbb{K})$ dada por

$$\begin{pmatrix}1&3&-1\\0&2&3\\ -1&0&2\end{pmatrix}$$

Razonad si $A$ es invertible y, si lo es, calculad su inversa.
